### ISSUE TITLE
Don't save empty tags

### ISSUE THREAD

**Issue by PossibleLlama** [PossibleLlama/worklog#72]
When creating a worklog with an empty tag, it should remove all empty tags. All tags should be trimmed of whitespace at the beginning and end of the string as well.

`worklog create --title "foo" --tags "foo  , \n, , bar"`

Should result in

``` yaml
...
title: "foo"
tags: ["bar", "foo"]
...
```

Note: These values are switched due to them also being sorted alphabetically.
